# name: Study Materials Service CI/CD

# on:
#   push:
#     branches: [main]
#     paths:
#       - 'material_service/**' 
#   # pull_request:
#   #   branches: [main]
#   #   paths:
#   #     - 'material_service/**'

# jobs:

#   # Service 1: Study Materials (DockerHub)
  
#   build-and-push-study-materials:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3
    
#     - name: Login to DockerHub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
    
#     - name: Build and push Study Materials
#       uses: docker/build-push-action@v5
#       with:
#         context: ./material_service
#         push: true
#         tags: |
#           ${{ secrets.DOCKER_USERNAME }}/study-materials:latest
#           ${{ secrets.DOCKER_USERNAME }}/study-materials:${{ github.sha }}
        
#         cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/material_service:latest
#         cache-to: type=inline


name: Material Service CI/CD (DockerHub)

on:
  push:
    branches: [main]
    paths:
      - 'material_service/**'
  pull_request:
    branches: [main]
    paths:
      - 'material_service/**'

jobs:
  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./material_service
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/material-service:latest
          ${{ secrets.DOCKER_USERNAME }}/material-service:${{ github.sha }}



